export const images = {
  logoWithTagline: require('../../assets/images/logo-with-tagline.png'),
  maintenance: require('../../assets/images/maintenance.png'),
  aircon: require('../../assets/images/aircon.png'),
  tires: require('../../assets/images/tires.png'),
  radiator: require('../../assets/images/radiator.png'),
  transmission: require('../../assets/images/transmission.png'),
  brake: require('../../assets/images/brake.png'),
  engine: require('../../assets/images/engine.png'),
  electricals: require('../../assets/images/electricals.png'),
  underchassis: require('../../assets/images/underchassis.png'),
  steeringwheel: require('../../assets/images/steeringwheel.png'),

  carwash: require('../../assets/images/carwash.png'),
  autoglass: require('../../assets/images/autoglass.png'),
  upholstery: require('../../assets/images/upholstery.png'),
  calibration: require('../../assets/images/calibration.png'),
  painting: require('../../assets/images/painting.png'),
  denting: require('../../assets/images/denting.png'),
  accessories: require('../../assets/images/accessories.png'),
  muffler: require('../../assets/images/muffler.png'),
  fabrication: require('../../assets/images/fabrication.png'),

  // unavailable: require('../../assets/images/coins.png'),
  // face: require("../../assets/images/face.png"),
  // faerie: require("../../assets/images/faerie.png"),
  // typing: require("../../assets/images/typing-message.gif"),
};
